version: "3.8"
services: 
  touristapi:
    container_name: tourist-api
    ports: 
      - "8081:80"
    build:        
      context: ./api
      dockerfile: Dockerfile
      labels: 
        - "tourist-api"
    environment: 
      - TOURIST_API_DB_CONNECTION_STRING=${TOURIST_API_DB_CONNECTION_STRING_DOCKER}
    volumes: 
      - "uploaded-files-volume:/app/wwwroot/uploadedfiles"
    depends_on: 
      - sqlserver
  sqlserver:
    container_name: sqlserver
    ports:
      - "1433:1433"
    image: mcr.microsoft.com/mssql/rhel/server:2019-CU1-rhel-8
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_SERVER_SA_PASSWORD}
    volumes:
      - sql-server-volume:/var/opt/mssql       
  touristfe:
    container_name: tourist-fe
    ports: 
      - "8080:80"
    build:
      context: ./front-end
      dockerfile: Dockerfile
      labels: 
        - "tourist-fe"       
    depends_on: 
      - touristapi
volumes: 
  sql-server-volume:        
    driver: local    
  uploaded-files-volume:        
    driver: local
    

